name: Download files

on:
  push:
    branches:
      - main
  schedule:
    - cron: "10 */1 * * *"
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: write
    env:
      USER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}
      SRC_NAME: ${{ secrets.REPO }}
      COUNT: 50

    steps:
      - uses: actions/checkout@v4

      - name: Checkout src repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.USER }}/${{ env.SRC_NAME }}
          token: ${{ secrets.GH_TOKEN }}
          path: ${{ env.SRC_NAME }}
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Update parameter
        run: |
          if [ "${{ github.event.schedule }}" == "15 14 * * 2" ]; then
            echo "COUNT=100" >> $GITHUB_ENV
          fi

      - name: Run download PDF
        # if: github.event.schedule != '5 */12 * * *'
        run: |
          count=${{ env.COUNT }}
          pushd ${{ env.SRC_NAME }} && 
          bash scripts/run-pdf.sh v1 $count &&
          popd

      - name: Git auto commit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_message: Automated update
          # commit_options: '--no-verify --signoff'
          # push_options: "--force"
          # file_pattern: "*.json *.docx *.doc *.pdf"
